components/authenticators/mutual-ssl-authenticator/src/main/java/org/wso2/carbon/identity/authenticator/mutualssl/MutualSSLAuthenticator.java

Creating PR to wso2/carbon-identity

Changes related to IDENTITY-2821

---

components/identity/org.wso2.carbon.identity.application.authentication.endpoint/pom.xml

Please refer to https://wso2.org/jira/browse/IDENTITY-3006

Fixing IDENTITY-3006 :- Added the jstl dependency to get authentication.endpoint web app working

---

components/identity/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/web/userstore_config/userstore-config-finish.jsp

$Subject. But haven't done smoke test..

Fixing https://wso2.org/jira/browse/IDENTITY-2384

---

components/identity/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/SAMLApplicationDAOImpl.java

Fix for https://wso2.org/jira/browse/IDENTITY-2295

Fixing IDENTITY-2295

---

components/identity/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/config/EmailConfigTransformer.java

Improvement for IDENTITY-2923

---

components/identity/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java
components/identity/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultAuthenticationRequestHandler.java
components/identity/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkConstants.java
components/identity/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/services/UserInformationRecoveryService.java
components/identity/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/store/UserStoreBasedIdentityDataStore.java
components/identity/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/util/UserIdentityManagementUtil.java
components/identity/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/util/Utils.java
components/identity/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/builders/SingleLogoutMessageBuilder.java
components/identity/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/processors/LogoutRequestProcessor.java

Fixing merge issue of pull/100 for commit b6086e97420cd824f039498faa5b7bf02f7ec897.

Fixing merge issue

---

components/identity/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/provisioning/impl/DefaultProvisioningHandler.java

Reverts wso2/carbon-identity#53

Revert "fixing IDENTITY-2939"

---

components/identity/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/provisioning/impl/DefaultProvisioningHandler.java

Reverts wso2/carbon-identity#108

Revert "Revert "fixing IDENTITY-2939""

---

components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/IdentityMgtEventListener.java
components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/dto/UserIdentityClaimsDO.java

Fixing IDENTITY-3086

---

components/agents/org.wso2.carbon.identity.entitlement.filter/pom.xml
components/agents/org.wso2.carbon.identity.entitlement.proxy/pom.xml
components/agents/org.wso2.carbon.identity.sso.agent/pom.xml
pom.xml

refactoring bundle dependencies of entitlement.filter, entitlement.proxy and sso.agent

---

components/agents/org.wso2.carbon.identity.sso.agent/pom.xml
components/claim-mgt/org.wso2.carbon.claim.mgt.ui/pom.xml
components/claim-mgt/org.wso2.carbon.claim.mgt/pom.xml
components/directory-server-manager/org.wso2.carbon.directory.server.manager.common/pom.xml
components/directory-server-manager/org.wso2.carbon.directory.server.manager.ui/pom.xml
components/directory-server-manager/org.wso2.carbon.directory.server.manager/pom.xml

refactoring copyrights and bundle dependencies of agents, claim-mgt, directory-server-manager

---

components/security/org.wso2.carbon.security.mgt/src/main/java/org/wso2/carbon/security/pox/POXSecurityHandler.java

POXSecurityHandler get invoked for SOAP requests and does not return SOAP faults incase of faults WSAS-1065 and adding fix of ESBJAVA-3416 due to missed it during solving merge conflicts

POXSecurityHandler fixes

---

features/claim-management/org.wso2.carbon.claim.mgt.server.feature/resources/conf/claim-config.xml

Added default claim mapping for uid

fix for IDENTITY-2908

---

components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/add.jsp
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/edit-finish.jsp
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/edit.jsp
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/index.jsp
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/remove-profile.jsp
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/set-finish.jsp

merge together with https://github.com/wso2/carbon-commons/pull/91

special character ui changes

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/resources/TenantConfig.properties

Fix for [1] needs to read the hostname verification property. 
[1] https://wso2.org/jira/browse/IDENTITY-2980

IDENTITY-2980 hostname verification property

---

components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java

IDENTITY-3223

---

components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtUtil.java

Fixing IDENTITY-3205 part ii : Fixing username used to create app role when application get created..
Refer comment [1]
https://wso2.org/jira/browse/IDENTITY-3205?focusedCommentId=98074&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-98074

Fixing IDENTITY-3205 : Fixing username used to create app role

---

components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/ApplicationMgtUtil.java

Having more debug logs would be helpful to narrow down issues like IDENTITY-3205 in future.

Adding more logs to ApplicationMgtUtil

---

components/scim/org.wso2.carbon.identity.scim.provider/src/main/java/org/wso2/carbon/identity/scim/provider/impl/SCIMUserManager.java

This patch is for improving performance of 
SCIM group PUT
SCIM group PATCH
SCIM group List and
SCIM user List
Operations.

SCIM update performance improvement

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-service-provider.jsp

Fixes for IDENTITY-2650

---

components/notification-mgt/org.wso2.carbon.identity.notification.mgt.email/src/main/java/org/wso2/carbon/identity/notification/mgt/email/EmailModuleConstants.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt.email/src/main/java/org/wso2/carbon/identity/notification/mgt/email/EmailSendingModule.java

Fixed Findbugs  major issues - 3
licence headers ok

org.wso2.carbon.identity.notification.mgt.email code refactored

---

components/sso-saml/org.wso2.carbon.identity.sso.saml.common/pom.xml
components/sso-saml/org.wso2.carbon.identity.sso.saml.common/src/main/java/org/wso2/carbon/identity/sso/saml/common/SAMLSSOProviderConstants.java
components/sso-saml/org.wso2.carbon.identity.sso.saml.common/src/main/java/org/wso2/carbon/identity/sso/saml/common/Util.java

Fixed Findbugs critical and major issues - 7
licence headers added

org.wso2.carbon.identity.sso.saml.common code refactored

---

components/notification-mgt/org.wso2.carbon.identity.notification.mgt/pom.xml
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/AbstractNotificationSendingModule.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/EventDistributionTask.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/NotificationManagementException.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/NotificationManagementUtils.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/NotificationMgtConfigBuilder.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/NotificationMgtConstants.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/internal/NotificationManagementServiceComponent.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/internal/NotificationManagementServiceDataHolder.java

Fixed Findbugs blocker, critical and major issues - 6
licence headers added

org.wso2.carbon.identity.notification.mgt code refactored

---

components/notification-mgt/org.wso2.carbon.identity.notification.mgt.json/pom.xml
components/notification-mgt/org.wso2.carbon.identity.notification.mgt.json/src/main/java/org/wso2/carbon/identity/notification/mgt/json/JsonMessageModule.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt.json/src/main/java/org/wso2/carbon/identity/notification/mgt/json/JsonModuleConstants.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt.json/src/main/java/org/wso2/carbon/identity/notification/mgt/json/bean/JsonEndpointInfo.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt.json/src/main/java/org/wso2/carbon/identity/notification/mgt/json/bean/JsonSubscription.java

Fixed Findbugs major issues - 8

org.wso2.carbon.identity.notification.mgt.json code refactored

---

components/policy-editor/org.wso2.carbon.policyeditor/pom.xml
components/policy-editor/org.wso2.carbon.policyeditor/src/main/java/org/wso2/carbon/policyeditor/PolicyEditorService.java
components/policy-editor/org.wso2.carbon.policyeditor/src/main/resources/META-INF/services.xml
components/policy-editor/org.wso2.carbon.policyeditor/src/main/resources/org/wso2/carbon/policyeditor/xsd/policies.xml
components/policy-editor/org.wso2.carbon.policyeditor/src/main/resources/org/wso2/carbon/policyeditor/xsd/ws-policy.xsd
components/policy-editor/org.wso2.carbon.policyeditor/src/main/resources/org/wso2/carbon/policyeditor/xsd/ws-securitypolicy.xsd
components/policy-editor/org.wso2.carbon.policyeditor/src/main/resources/org/wso2/carbon/policyeditor/xsd/wsrm-policy.xsd
components/policy-editor/org.wso2.carbon.policyeditor/src/main/resources/org/wso2/carbon/policyeditor/xsd/wssecurity-secext-1.0.xsd
components/policy-editor/org.wso2.carbon.policyeditor/src/main/resources/org/wso2/carbon/policyeditor/xsd/wssecurity-utility-1.0.xsd

Fixed Findbugs critical and major issues - 14
licence headers added

org.wso2.carbon.policyeditor code refactored

---

components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/org/wso2/carbon/policyeditor/ui/i18n/JSResources.properties
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/org/wso2/carbon/policyeditor/ui/i18n/Resources.properties
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/css/local-styles.css
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/docs/userguide.html
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/index.jsp
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/policy-editor-service-stub.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/policy-editor.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/sax-policy-menu.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/sax-tree.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/prettyPrinter_ajaxprocessor.jsp
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/xslt/XMLFormatter.xsl

org.wso2.carbon.policyeditor.ui code refactored

---

components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/org/wso2/carbon/policyeditor/ui/i18n/JSResources.properties
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/org/wso2/carbon/policyeditor/ui/i18n/Resources.properties
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/css/local-styles.css
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/docs/userguide.html
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/index.jsp
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/policy-editor-service-stub.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/policy-editor.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/sax-policy-menu.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/js/sax-tree.js
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/prettyPrinter_ajaxprocessor.jsp
components/policy-editor/org.wso2.carbon.policyeditor.ui/src/main/resources/web/policyeditor/xslt/XMLFormatter.xsl

Reverts wso2/carbon-identity#368

Revert "org.wso2.carbon.policyeditor.ui code refactored"

---

components/user-store/org.wso2.carbon.identity.user.store.remote/pom.xml
components/user-store/org.wso2.carbon.identity.user.store.remote/src/main/java/org/wso2/carbon/identity/user/store/remote/CarbonRemoteUserStoreManger.java
components/user-store/org.wso2.carbon.identity.user.store.remote/src/main/java/org/wso2/carbon/identity/user/store/remote/internal/CarbonRemoteUserStoreDSComponent.java
components/user-store/org.wso2.carbon.identity.user.store.remote/src/test/java/org/wso2/carbon/identity/user/store/remote/CarbonRemoteUserStoreMangerTest.java
components/user-store/org.wso2.carbon.user.cassandra/pom.xml
components/user-store/org.wso2.carbon.user.cassandra/src/main/java/org/wso2/carbon/user/cassandra/CFConstants.java
components/user-store/org.wso2.carbon.user.cassandra/src/main/java/org/wso2/carbon/user/cassandra/CassandraRoleContext.java
components/user-store/org.wso2.carbon.user.cassandra/src/main/java/org/wso2/carbon/user/cassandra/CassandraUserStoreManager.java
components/user-store/org.wso2.carbon.user.cassandra/src/main/java/org/wso2/carbon/user/cassandra/Util.java
components/user-store/org.wso2.carbon.user.cassandra/src/main/java/org/wso2/carbon/user/cassandra/internal/CassandraUserStoreManagerServiceComponent.java
components/user-store/org.wso2.carbon.user.cassandra/src/main/java/org/wso2/carbon/user/cassandra/internal/CassandraUserStoreManagerServiceDataHolder.java
components/user-store/pom.xml
components/user-store/usrmgrtest/src/org/wso2/carbon/user/multicredentials/test/BasicTest.java

Updated license headers
Fixed all blocker issues
Fixed all fixable critical issues
Fixed all fixable major issues
Fixed most minor issues

Refactored user store

---

components/claim-mgt/org.wso2.carbon.claim.mgt/src/main/java/org/wso2/carbon/claim/mgt/dto/ClaimDTO.java

Fixing issue [IDENTITY-3104] on jira. Commited the changes.

claim URI spaces trimmed

---

components/provisioning/org.wso2.carbon.identity.provisioning.connector.scim/src/main/java/org/wso2/carbon/identity/provisioning/connector/scim/SCIMProvisioningConnector.java
components/provisioning/org.wso2.carbon.identity.provisioning/src/main/java/org/wso2/carbon/identity/provisioning/ProvisioningOperation.java
components/provisioning/org.wso2.carbon.identity.provisioning/src/main/java/org/wso2/carbon/identity/provisioning/listener/DefaultInboundUserProvisioningListener.java
components/scim/org.wso2.carbon.identity.scim.common/src/main/java/org/wso2/carbon/identity/scim/common/impl/DefaultSCIMProvisioningHandler.java
components/scim/org.wso2.carbon.identity.scim.common/src/main/java/org/wso2/carbon/identity/scim/common/impl/ProvisioningClient.java
components/scim/org.wso2.carbon.identity.scim.provider/src/main/java/org/wso2/carbon/identity/scim/provider/impl/SCIMUserManager.java
components/scim/org.wso2.carbon.identity.scim.provider/src/main/java/org/wso2/carbon/identity/scim/provider/resources/UserResource.java
pom.xml

Reverts wso2/carbon-identity#442

Revert "Identity 3304 - Implement SCIM PATCH operation for Users"

---

components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.ui/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/ui/authenticator/SAML2SSOUIAuthenticator.java

Fixing NPE which occurs when try to logout from unauthorized user account

---

components/user-mgt/org.wso2.carbon.identity.user.profile.ui/pom.xml
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/add.jsp
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/index.jsp
components/user-mgt/org.wso2.carbon.identity.user.profile/pom.xml
components/user-mgt/org.wso2.carbon.identity.user.profile/src/main/java/org/wso2/carbon/identity/user/profile/mgt/UserProfileAdmin.java

Identity-343 Multiple User Profiles feature is broken in IS 5.0.0

Identity-343 Multiple User Profiles feature is broken in IS 5.0.0

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java

Fixing https://wso2.org/jira/browse/IDENTITY-3072

Fixing IDENTITY-3072

---

components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/processors/LogoutRequestProcessor.java

Adding the ability of Logout in Tenancy mode, if the Entity Id is used to specify a tenant.
Removing 71f44fcd028bc2cf5b8b6becf86b855cd4bc226f commit.

Fixing JIRA IDENTITY-2619

---

components/application-authenticators/org.wso2.carbon.identity.application.authenticator.fido/pom.xml
components/carbon-authenticators/iwa-authenticator/org.wso2.carbon.identity.authenticator.iwa.ui/pom.xml
components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.common/pom.xml
components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.ui/pom.xml
components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.ui/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/ui/authenticator/SAML2SSOUIAuthenticator.java
components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.ui/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/ui/client/SAML2SSOAuthenticationClient.java
components/provisioning/org.wso2.carbon.identity.provisioning.connector.scim/pom.xml

IDENTITY-3389 Move dependency versions from component level poms to master pom

IDENTITY-3389 Move dependency versions from component level poms to master pom

---

components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/builders/SingleLogoutMessageBuilder.java

Fix for [1]
[1] https://wso2.org/jira/browse/IDENTITY-2853

Fix for IDENTITY-2853

---

features/identity-mgt/org.wso2.carbon.identity.mgt.server.feature/resources/email-admin-config.xml

URL encoded the all the places where the user-name URL is used in the templates.

Fixing JIRA IDENTITY-2933

---

components/sts/org.wso2.carbon.identity.sts.passive.ui/pom.xml
components/sts/org.wso2.carbon.identity.sts.passive.ui/src/main/java/org/wso2/carbon/identity/sts/passive/ui/PassiveSTS.java

Separate HTML from Java in Passive STS redirection page.
Possibility of giving an html page (optional) for passive sts redirect page.

Fixing JIRA IDENTITY:3347

---

features/passive-sts/org.wso2.carbon.identity.sts.passive.server.feature/resources/p2.inf
features/passive-sts/org.wso2.carbon.identity.sts.passive.server.feature/resources/sts_redirect.html

Adding sts response html file for [1]
[1] https://wso2.org/jira/browse/IDENTITY-3347

Adding PassiveSTS response html file for IDENTITY-3347

---

components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/dao/IdPManagementDAO.java

This fixes the issue of 
When no provisioning config properties are available, provisioning connector cannot be enabled (For custom provisioning connectors)

fix for IDENTITY-3394

---

components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/role-mgt.jsp

Now only shows add new role option if the selected user-store is not read-only

Fix for IDENTITY-946

---

components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/edit-users.jsp
components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/role-mgt.jsp
components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/view-users.jsp

Please review the logic of retrieving from the session.

Fix for Identity 3307

---

components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/edit-permissions-finish.jsp

Error properly handled when users attempty wrongfully assing permission to roles

Fix for IDENTITY-688

---

components/user-manager/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/role-mgt.jsp

Reverts wso2/carbon-identity#575

Revert "Fix for IDENTITY-946"

---

components/identity-core/org.wso2.carbon.identity.base/src/main/java/org/wso2/carbon/identity/base/IdentityConstants.java
components/openid/org.wso2.carbon.identity.provider/pom.xml
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/OpenIDProvider.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/OpenIDServerAssociationStore.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/OpenIDServerManager.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/PrivateAssociationCryptoStore.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/PrivateAssociationReplicationStore.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/dao/OpenIDAssociationDAO.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/dao/OpenIDSQLQueries.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/replication/AssociationCleanupService.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/replication/AssociationClusterMessage.java
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/replication/OpenIDAssociationReplicationManager.java

First part of the improvements done for OpenID flow.

Performance improvement for OpenID

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/list-service-providers.jsp

Adding Pagination functionality to the Service Provider list.

Fixing JIRA:IDENTITY-2895

---

components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/google/GoogleOAuth2Authenticator.java
components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/live/WindowsLiveOAuth2Authenticator.java
components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso/pom.xml
components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/SAML2SSOAuthenticator.java

IDENTITY-3253

---

components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.common/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/common/builders/AuthenticationRequestBuilder.java

$subject to avoid code duplication.

Refactoring AuthenticationRequestBuilder

---

components/provisioning/org.wso2.carbon.identity.provisioning.connector.salesforce/pom.xml
components/provisioning/org.wso2.carbon.identity.provisioning.connector.spml/pom.xml

Removing unnecessary charon dependencies from provisioning connectors.

Removing unused dependencies

---

components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.ui/src/main/resources/web/sso-acs/authFailure.jsp

Fixing IDENTITY-3345

---

components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java

Reading 'SaaS enabled' from correct column in the database

---

components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.ui/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/ui/SSOAssertionConsumerService.java

Fixing IDENTITY-2663

---

components/entitlement/org.wso2.carbon.identity.entitlement.ui/src/main/resources/META-INF/component.xml
components/entitlement/org.wso2.carbon.identity.entitlement.ui/src/main/resources/web/entitlement/index.jsp
components/entitlement/org.wso2.carbon.identity.entitlement.ui/src/main/resources/web/entitlement/my-pdp.jsp
components/entitlement/org.wso2.carbon.identity.entitlement.ui/src/main/resources/web/entitlement/pdp-manage.jsp
components/entitlement/org.wso2.carbon.identity.entitlement.ui/src/main/resources/web/entitlement/show-policy-version.jsp
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/resources/META-INF/services.xml

The permission model for EntitlementAdminService and EntitilementPolicyAdminService are made more fine-grained.

Fix for IDENTITY-3470

---

components/identity-mgt/org.wso2.carbon.identity.mgt/pom.xml
components/notification-mgt/org.wso2.carbon.identity.notification.mgt.email/pom.xml
components/provisioning/org.wso2.carbon.identity.provisioning.connector.scim/pom.xml
components/user-store/org.wso2.carbon.identity.user.store.configuration/pom.xml
pom.xml

merge this after releasing apacheds orbit bundle 1.5.7.wso2v4

fix building problems with java 8

---

components/identity-core/org.wso2.carbon.identity.base/src/main/java/org/wso2/carbon/identity/base/IdentityConstants.java
features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml

Adding optional configs to configure openid private association store

---

components/scim/org.wso2.carbon.identity.scim.common/src/main/java/org/wso2/carbon/identity/scim/common/listener/SCIMUserOperationListener.java

Reverts wso2/carbon-identity#763

Revert "fixing IDENTITY-3484"

---

components/scim/org.wso2.carbon.identity.scim.common/src/main/java/org/wso2/carbon/identity/scim/common/listener/SCIMUserOperationListener.java

Reverts wso2/carbon-identity#811

Fixing IDENTITY-3484

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java

Fixing issue reported in mail thread: "[Dev] at_hash hash size" by udara@wso2.com

---

components/identity-mgt/org.wso2.carbon.identity.mgt/pom.xml

Fix for [1].
[1] https://wso2.org/jira/browse/IDENTITY-3514

avoid exporting internal package in identity.mgt component

---

components/user-mgt/org.wso2.carbon.user.mgt.workflow/pom.xml

IDENTITY-2904 Importing AbstractUserOperationEventListener introducedin 2904 fix to user.mgt.workflow component

IDENTITY-2904 Importing AbstractUserOperationEventListener introducedin 2904 fix to user.mgt.workflow component

---

components/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/add-finish.jsp
components/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/add.jsp
components/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/edit-finish.jsp
components/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/edit.jsp

This reverts commit d1b439ceb0d88e3241b04252066613009edabbcc.

Revert "Showing Application Token Grant type in OAuth/OpenId UI"

---

components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/web/userstore_config/userstore-config-finish.jsp

Removing Character encoders in UI

Fixing IDENTITY-3481

---

features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/application-authentication.xml

In the code , it reads the SAML2SSOManager from the config, but in the config it has a commented configuration as SAMLSSOManager.

Config rename SAMLSSOManager to SAML2SSOManager

---

components/sso-saml/org.wso2.carbon.identity.sso.saml/pom.xml
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/validators/SAML2HTTPRedirectDeflateSignatureValidator.java

Had import slf4j as import package without bundling within the feature, so had to remove to avoid unnecessary dependency when using this feature on cdmf.

Removed slf4j - unnecessary import package

---

components/carbon-authenticators/saml2-sso-authenticator/org.wso2.carbon.identity.authenticator.saml2.sso.ui/src/main/java/org/wso2/carbon/identity/authenticator/saml2/sso/ui/SSOAssertionConsumerService.java

Fixing IDENTITY-3536

---

components/user-mgt/org.wso2.carbon.identity.user.profile.ui/pom.xml
components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/set-finish.jsp

Fixing IDENTITY-3628

---

features/xacml/org.wso2.carbon.identity.xacml.server.feature/resources/entitlement.properties

Adding xacml policy loading file path property for [1]
[1] https://wso2.org/jira/browse/IDENTITY-3649

Adding xacml policy loading file path property for IDENTITY-3649

---

components/security-mgt/org.wso2.carbon.security.mgt.ui/pom.xml
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/add-keystore-finish.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/add-keystore-step2.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/delete-cert.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/delete-keystore.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/import-cert-finish.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/import-cert.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/keystore-mgt.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/keystoremgt/view-keystore.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/securityconfig/add-security.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/securityconfig/index.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/securityconfig/remove-security.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/securityconfig/ut-ks-advance.jsp
components/security-mgt/org.wso2.carbon.security.mgt.ui/src/main/resources/web/securityconfig/view-scenario-detail_ajaxprocessor.jsp

Added the OWASP encoding to prevent possible XSS attacks for the "security-mgt". Please review and merge.

Added the OWASP encoding to prevent possible XSS attacks.

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/saml/SAML2BearerGrantHandler.java

Adding more informative debug logs which useful to narrow down future issues.

IDENTITY-3635

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-local-service-provider.jsp
components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-service-provider.jsp

Fixing XSS regression in application.mgt.ui component due to encoding

Fixing XSS regression in application.mgt.ui

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/change-passwd-finish.jsp
components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/change-passwd.jsp

Removed encoding for "returnPath" variable by introducing "trustedReturnPath" which only accepts trusted values of "returnPath".

Fixing IDENTITY-3697

---

components/workflow-mgt/org.wso2.carbon.identity.workflow.mgt.ui/src/main/resources/web/workflow-mgt/wf-request-list.jsp

IDENTITY-3528 Error while adding datepicker for selecting date range with jquery 1.6.0

---

components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/index.jsp

reformatted the code to avoid spaces for the uri attribute.

reformatted the code

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/cache/SessionContextCache.java

Fixing $subject, when it cannot find a session entry from database.

Fixing NPE in SessionContextCache

---

components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/pom.xml
components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/java/org/wso2/carbon/identity/user/store/configuration/ui/client/UserStoreConfigAdminServiceClient.java
components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/UserstoreConfigAdminService.wsdl
components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/web/userstore_config/userstore-config.jsp
components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/web/userstore_config/validateconnection-ajaxprocessor.jsp
components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/UserStoreConfigAdminService.java
components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/utils/IdentityUserStoreMgtException.java
pom.xml
service-stubs/identity/org.wso2.carbon.identity.user.store.configuration.stub/src/main/resources/UserStoreConfigAdminService.wsdl

Fixing IDENTITY-3696

---

components/user-mgt/org.wso2.carbon.identity.user.profile.ui/src/main/resources/web/userprofile/edit.jsp

reformatting the code.

---

components/application-authenticators/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/pip/DefaultAttributeFinder.java
components/oauth/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/util/ClaimUtil.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/SAMLAssertionClaimsCallback.java
components/provisioning/org.wso2.carbon.identity.provisioning/src/main/java/org/wso2/carbon/identity/provisioning/OutboundProvisioningManager.java
components/provisioning/org.wso2.carbon.identity.provisioning/src/main/java/org/wso2/carbon/identity/provisioning/listener/DefaultInboundUserProvisioningListener.java
components/scim/org.wso2.carbon.identity.scim.common/src/main/java/org/wso2/carbon/identity/scim/common/listener/SCIMUserOperationListener.java

Fixing code that could possibly break due to previous fix for the same issue

Fixing IDENTITY-3581

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java

Doing $subject to change the way it retrieve the UserStoreManager for given domain from user.core.

Refactoring DefaultClaimHandler

---

components/security-mgt/org.wso2.carbon.security.mgt/src/main/java/org/wso2/carbon/security/SecurityServiceHolder.java
components/security-mgt/org.wso2.carbon.security.mgt/src/main/java/org/wso2/carbon/security/internal/SecurityMgtServiceComponent.java
components/security-mgt/org.wso2.carbon.security.mgt/src/main/java/org/wso2/carbon/security/util/ServerCrypto.java

related to issue https://wso2.org/jira/browse/IDENTITY-1982

fix sts issue related to tenant unloading.

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/edit-user-roles.jsp

fixing identity 3759

---

components/carbon-authenticators/mutual-ssl-authenticator/org.wso2.carbon.identity.authenticator.mutualssl/pom.xml
features/carbon-authenticators/mutual-ssl-authenticator/org.wso2.carbon.identity.authenticator.mutualssl.feature/pom.xml
features/carbon-authenticators/mutual-ssl-authenticator/pom.xml
pom.xml

Fixing IDENTITY-3822

---

components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/dto/UserIdentityClaimsDO.java

Fix for IDENTITY-3860

---

components/agents/org.wso2.carbon.identity.sso.agent/src/main/java/org/wso2/carbon/identity/sso/agent/openid/OpenIDManager.java

Add queryParams set in travelocity.parameters for openID login

Add queryParams set in travelocity.parameters for openID login

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/userstore/user-role-search.jsp

Enable listing results when user hits enter instead of clicking search roles button.

fix for 3872

---

components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/web/userstore_config/enable-disable-userstores.jsp

Fix-for-3804

---

components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/facebook/FacebookAuthenticator.java
components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/google/GoogleOAuth2AuthenticationConstant.java
components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/google/GoogleOAuth2Authenticator.java
components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/live/WindowsLiveOAuth2Authenticator.java
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit.jsp
features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/application-authentication.xml

Removing Oauth, Token and UserInfo endpoint from ui.

Fix for 3632

---

components/application-authenticators/org.wso2.carbon.identity.application.authenticator.fido/src/main/java/org/wso2/carbon/identity/application/authenticator/fido/FIDOAuthenticator.java

Set authenticated user to the subject of the context.

Fix-for-3901

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/user-mgt.jsp

fixing IDENTITY-3891

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-service-provider-finish.jsp
components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-service-provider.jsp

https://wso2.org/jira/browse/IDENTITY-3913

Fixing - IDENTITY-3913

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/org/wso2/carbon/userstore/ui/i18n/Resources.properties
components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/change-passwd.jsp

https://wso2.org/jira/browse/IDENTITY-3530

Fixing - IDENTITY-3530

---

components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManager.java

https://wso2.org/jira/browse/IDENTITY-3933

Fixing - IDENTITY-3933

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-local-service-provider.jsp

Fixing the illegalexception when updating the resident SP.

---

features/openid/org.wso2.carbon.identity.provider.server.feature/pom.xml
features/sts/org.wso2.carbon.sts.server.feature/pom.xml

Reverts wso2/carbon-identity#1315

Revert "removing sts mgt and store from sts server feature"

---

components/application-mgt/org.wso2.carbon.identity.application.common/pom.xml
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/util/IdentityApplicationManagementUtil.java
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/java/org/wso2/carbon/idp/mgt/ui/util/IdPManagementUIUtil.java
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit-local.jsp

Moving getPropertySetStatrtsWith method to IdpManagementUIUtil from IdentityApplicationManagementUtil.java to remove unnecessary dependencies in application.common

Revision fix for 3515

---

components/workflow-mgt/org.wso2.carbon.identity.workflow.impl.ui/src/main/resources/web/workflow-impl/update-bps-profile.jsp

Added autocomplete off and placeholder for the password field.

Fix-for-3908

---

components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/java/org/wso2/carbon/idp/mgt/ui/util/IdPManagementUIUtil.java
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-add-finish.jsp
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-delete-finish.jsp
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit-finish.jsp
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit-load.jsp
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit.jsp
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-list-load.jsp

https://wso2.org/jira/browse/IDENTITY-3834

Fixing - IDENTITY-3834

---

components/workflow-mgt/org.wso2.carbon.identity.workflow.mgt.ui/src/main/resources/web/workflow-mgt/add-association.jsp

Set disabled false by checking operation in the association.

Fix-for-3918

---

components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/LocalRole.java
components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/provisioning/impl/DefaultProvisioningHandler.java
components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java
components/identity-mgt/org.wso2.carbon.identity.mgt/pom.xml
components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/RecoveryProcessor.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authcontext/JWTTokenGenerator.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/TokenMgtDAO.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/SAMLAssertionClaimsCallback.java
components/provisioning/org.wso2.carbon.identity.provisioning/src/main/java/org/wso2/carbon/identity/provisioning/dao/ProvisioningManagementDAO.java
components/scim/org.wso2.carbon.identity.scim.provider/src/main/java/org/wso2/carbon/identity/scim/provider/impl/SCIMUserManager.java
components/security-mgt/org.wso2.carbon.security.mgt/src/main/java/org/wso2/carbon/security/util/ServicePasswordCallbackHandler.java
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/UserRegistrationService.java
components/user-mgt/org.wso2.carbon.user.mgt.ui/pom.xml
components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/add-finish.jsp
components/user-store/org.wso2.carbon.identity.user.store.configuration/pom.xml
components/user-store/org.wso2.carbon.identity.user.store.configuration/src/main/java/org/wso2/carbon/identity/user/store/configuration/UserStoreConfigAdminService.java

fixing IDENTITY-4001

---

components/provisioning/org.wso2.carbon.identity.provisioning.connector.google/src/main/java/org/wso2/carbon/identity/provisioning/connector/google/GoogleProvisioningConnector.java

Re-aranging debug logs to avoid unnecessary info

---

components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/IdentityMgtConfig.java
components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/IdentityMgtEventListener.java
components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/constants/IdentityMgtConstants.java
features/identity-mgt/org.wso2.carbon.identity.mgt.server.feature/resources/identity-mgt.properties

Removing unwanted properties from identity-mgt.properties file

---

components/oauth/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/add.jsp
components/sso-saml/org.wso2.carbon.identity.sso.saml.ui/src/main/resources/web/sso-saml/add_service_provider.jsp
components/sso-saml/org.wso2.carbon.identity.sso.saml.ui/src/main/resources/web/sso-saml/update_claims.jsp

https://wso2.org/jira/browse/IDENTITY-3912

Fixing IDENTITY-3912

---

components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityCoreConstants.java
components/workflow-mgt/org.wso2.carbon.identity.workflow.mgt/src/main/java/org/wso2/carbon/identity/workflow/mgt/util/WorkflowManagementUtil.java

Reverts wso2/carbon-identity#1352

Reverts wso2/carbon-identity#1352

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-service-provider.jsp
components/sso-saml/org.wso2.carbon.identity.sso.saml.ui/src/main/resources/web/sso-saml/remove_service_providers.jsp

https://wso2.org/jira/browse/IDENTITY-3974?focusedCommentId=111488&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-111488

Fixing the issue mentioned in the IDENTITY-3974 comment.

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/DefaultIDTokenBuilder.java

Passing miliseconds to date object.

Fix for 3009

---

components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManager.java

Fixing - IDENTITY-3133

---

components/entitlement/org.wso2.carbon.identity.entitlement.ui/src/main/resources/META-INF/component.xml
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/internal/EntitlementServiceComponent.java
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/resources/META-INF/services.xml
components/oauth/org.wso2.carbon.identity.oauth.ui/src/main/resources/META-INF/component.xml
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuth2ServiceComponent.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/resources/META-INF/services.xml
components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/user-mgt.jsp

Add new permission to entitlement service.

Fix for 2197

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/change-passwd-finish.jsp
components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/change-passwd.jsp

Testing whether the old password field is undefined.

Fix-for-4063

---

components/oauth/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/add.jsp
components/oauth/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/edit.jsp

Fixing Identity 3948

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/role/role-mgt.jsp

Fixing IDENTITY-4062

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthAdminService.java

https://wso2.org/jira/browse/IDENTITY-4064

Fixing - IDENTITY-4064

---

components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/SAMLSSOConstants.java
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/admin/FileBasedConfigManager.java
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/processors/SPInitLogoutRequestProcessor.java
features/sso-saml/org.wso2.carbon.identity.sso.saml.server.feature/resources/sso-idp-config.xml

Fix for 4070 and adding correct error logs in SPInitLogoutRequestProcessor.

Fix for 4070

---

components/idp-mgt/org.wso2.carbon.idp.mgt.ui/pom.xml
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit-local.jsp
components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManagementService.java
components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManager.java

Validating Session idele time out and Remember me time in resident identity provider

Fix for 4072

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/user/user-mgt.jsp

https://wso2.org/jira/browse/IDENTITY-4075

Fixing - IDENTITY-4075

---

components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/saml/SAML2TokenBuilder.java

Reverts wso2/carbon-identity#1447

Revert "Identity 4086"

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/config/OAuthServerConfiguration.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/AccessTokenIssuer.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/OAuthTokenReqMessageContext.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/AbstractAuthorizationGrantHandler.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java

IDENTITY-4111

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/OAuth2TokenValidationService.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dto/OAuth2IntrospectionResponseDTO.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/TokenValidationHandler.java

1. Refactored the method findOAuthConsumerIfTokenIsValid and deprecated it.
2. Introduced a new method buildIntrospectionResponse

Adding introspection support

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authz/AuthorizationHandlerManager.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authz/OAuthAuthzReqMessageContext.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authz/handlers/AbstractResponseTypeHandler.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authz/handlers/CodeResponseTypeHandler.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/authz/handlers/TokenResponseTypeHandler.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java

Fixes for TokenResponseTypeHandler.

Fixing IDENTITY-4111

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/tokenprocessor/EncryptionDecryptionPersistenceProcessor.java

$subject as discussed with in the thread "OAuth clientId in SP_INBOUND_AUTH" in dev@wso2.com

Avoid encrypting client id with EncryptionDecryptionPersistenceProcessor

---

components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java

This reverts commit 8f68b54cc2571310d2ca5cf651ce89d9f507d236.

Revert "Update IdentityUtil.java"

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/config/builder/FileBasedConfigurationBuilder.java
components/identity-core/org.wso2.carbon.identity.base/src/main/java/org/wso2/carbon/identity/base/IdentityConstants.java
components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java
components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManager.java
components/oauth/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/edit.jsp
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/admin/FileBasedConfigManager.java
features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml

Reverts wso2/carbon-identity#1400

Revert "Fixing - IDENTITY-3959"

---

components/user-store/org.wso2.carbon.identity.user.store.configuration.ui/src/main/resources/web/userstore_config/userstore-config.jsp

Fixing test connection function for JDBC user store configuration,

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/config/builder/FileBasedConfigurationBuilder.java
components/identity-core/org.wso2.carbon.identity.base/src/main/java/org/wso2/carbon/identity/base/IdentityConstants.java
components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java
components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/IdentityProviderManager.java
components/oauth/org.wso2.carbon.identity.oauth.ui/src/main/resources/web/oauth/edit.jsp
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/admin/FileBasedConfigManager.java
features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml

Reverts wso2/carbon-identity#1474

Revert "Revert "Fixing - IDENTITY-3959""- Jayanga

---

components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/UserAdmin.java
components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/internal/UserMgtDSComponent.java
components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/listeners/UserMgtAuditLogger.java

Adding userMgtAuditLogger and removing audit logs from userAdmin

---

components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/SAMLSSOConstants.java
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/servlet/SAMLSSOProviderServlet.java
components/sts/org.wso2.carbon.identity.sts.passive.ui/src/main/java/org/wso2/carbon/identity/sts/passive/ui/PassiveSTS.java
components/user-mgt/org.wso2.carbon.user.mgt.workflow/src/main/java/org/wso2/carbon/user/mgt/workflow/userstore/AddUserWFRequestHandler.java
components/workflow-mgt/org.wso2.carbon.identity.workflow.impl/src/main/java/org/wso2/carbon/identity/workflow/impl/dao/BPSProfileDAO.java

Please don't merge this PR until all the comments are addressed.

Fixing PR Comments

---

components/idp-mgt/org.wso2.carbon.idp.mgt/pom.xml
components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/internal/IdPManagementServiceComponent.java
components/idp-mgt/org.wso2.carbon.idp.mgt/src/main/java/org/wso2/carbon/idp/mgt/listener/IDPMgtAuditLogger.java

Reverts wso2/carbon-identity#1508

Revert "Revert "audit loggers for IDPs""-FIxingBranch

---

components/application-mgt/org.wso2.carbon.identity.application.mgt/pom.xml
components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/internal/ApplicationManagementServiceComponent.java
components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationMgtAuditLogger.java
components/notification-mgt/org.wso2.carbon.identity.notification.mgt/src/main/java/org/wso2/carbon/identity/notification/mgt/NotificationMgtConfigBuilder.java

Reverts wso2/carbon-identity#1507

Revert "Revert "IDENTITY-4099- FOR SP creation/edit/delete""-FixingBranch

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/Constants.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/UserRegistrationAdminServiceClient.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/pom.xml
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/create-account.jsp
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/registration.jsp
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/UserRegistrationService.java
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/dto/UserFieldDTO.java
service-stubs/identity/org.wso2.carbon.identity.user.registration.stub/src/main/resources/UserRegistrationAdminService.wsdl

https://wso2.org/jira/browse/IDENTITY-4154
https://wso2.org/jira/browse/IDENTITY-4152
Added the facility to show error messages without page refresh.
Moved the user exist search to a service.
Fixed the footer misalignment scenarios. [(IDENTITY-4152)] (https://wso2.org/jira/browse/IDENTITY-4152)
Added a response to show to user after successful signup.

Fixing - IDENTITY-4154, IDENTITY-4152

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkUtils.java
components/entitlement/org.wso2.carbon.identity.entitlement.common/src/main/java/org/wso2/carbon/identity/entitlement/common/InMemoryPersistenceManager.java
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/EntitlementUtil.java
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/pap/PAPPolicyReader.java
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/policy/PolicyRequestBuilder.java
components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java
components/policy-editor/org.wso2.carbon.policyeditor/src/main/java/org/wso2/carbon/policyeditor/PolicyEditorService.java
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/UserRegistrationService.java
components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/bulkimport/CSVUserBulkImport.java

Fixed veracode issues according to support branch.

Fixing  IDENTITY-4176,4177

---

components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/Claim.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/ClaimConfig.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/ClaimMapping.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/FederatedAuthenticatorConfig.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/IdentityProvider.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/InboundAuthenticationConfig.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/InboundAuthenticationRequestConfig.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/LocalAndOutboundAuthenticationConfig.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/PermissionsAndRoleConfig.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/model/ServiceProvider.java
components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/util/IdentityApplicationConstants.java

Reverts wso2/carbon-identity#1407

Revert "Fixing IDENTITY-2720"

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-service-provider.jsp

https://wso2.org/jira/browse/IDENTITY-4059

Fixed - IDENTITY-4059

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/basicauth.jsp

related with https://github.com/wso2/product-is/pull/360

Fixing Identity 3638

---

components/identity-core/org.wso2.carbon.identity.base/src/main/java/org/wso2/carbon/identity/base/IdentityConstants.java
components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java
features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml

https://wso2.org/jira/browse/IDENTITY-4187

Fixing - IDENTITY-4187

---

components/user-mgt/org.wso2.carbon.identity.user.account.association/src/main/java/org/wso2/carbon/identity/user/account/association/UserAccountAssociationService.java
components/user-mgt/org.wso2.carbon.identity.user.account.association/src/main/java/org/wso2/carbon/identity/user/account/association/UserAccountConnectorImpl.java
components/user-mgt/org.wso2.carbon.identity.user.account.association/src/main/java/org/wso2/carbon/identity/user/account/association/dao/UserAccountAssociationDAO.java

Fixing IDENTITY-4188

---

components/user-mgt/org.wso2.carbon.identity.user.account.association/src/main/java/org/wso2/carbon/identity/user/account/association/util/UserAccountAssociationUtil.java

$Subject.
Removing unused method UserAccountAssociationUtil.getDomainName()

Re-factoring related to IDENTITY-4188

---

components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/admin/FileBasedConfigManager.java

Fix for IDENTITY-4192

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/TenantDataManager.java

Fix for IDENTITY-4185

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/create-account.jsp

https://wso2.org/jira/browse/IDENTITY-4210

Fixing - IDENTITY-4210

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/UserRegistrationAdminServiceClient.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/registration.jsp
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/UserRegistrationException.java
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/UserRegistrationService.java
service-stubs/identity/org.wso2.carbon.identity.user.registration.stub/src/main/resources/UserRegistrationAdminService.wsdl

https://wso2.org/jira/browse/IDENTITY-4207

Fixed - IDENTITY-4207

---

features/authentication-framework/org.wso2.carbon.identity.application.authentication.framework.server.feature/resources/application-authentication.xml
features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml
features/sso-saml/org.wso2.carbon.identity.sso.saml.server.feature/resources/sso-idp-config.xml

https://wso2.org/jira/browse/IDENTITY-4195

Fixed - IDENTITY-4195

---

components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/AttributeCallbackHandler.java

All claims returns as http://wso2.org/claims in passivests in SAML Assertion, and fix the issue from this PR

Remove unnecessary if statement to load claims

---

components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/add-service-provider.jsp
components/application-mgt/org.wso2.carbon.identity.application.mgt.ui/src/main/resources/web/application/configure-service-provider.jsp

Regex formatted.

---

components/agents/org.wso2.carbon.identity.sso.agent/src/main/java/org/wso2/carbon/identity/sso/agent/saml/SAML2SSOManager.java

Resolving Assertion Encryption issue.

---

components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/live/WindowsLiveOAuth2Authenticator.java
components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/yahoo/YahooOAuth2Authenticator.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/model/AuthenticatedUser.java

Changed the AuthenticatedUser calss to use UserCoreUtill class to get username.
https://wso2.org/jira/browse/IDENTITY-4233

Fixed - IDENTITY-4233

---

components/user-mgt/org.wso2.carbon.user.mgt.ui/src/main/resources/web/userstore/add-user-role.jsp

hiding Bulk User Import option if no user store has it enabled.

---

features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/identity.xml

[Engineering][IS510] URL building with Placeholders in identity.xml

Changed the ${carbon.mgt.port.https} to ${carbon.management.port} in identity.xml

---

components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/IdentityUtil.java

[Engineering][IS510] URL building with Placeholders in identity.xml

Changed the functionality to get non proxy port from system property for ${carbon.management.port}

---

components/oauth/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthAdminService.java

Reverts wso2/carbon-identity#1649

Revert "fixing incorrect sub attribute in oauth"

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthAdminService.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/config/OAuthServerConfiguration.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/internal/OAuthServiceComponent.java

Reverts wso2/carbon-identity#1647

Revert "Prabath a"

---

components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/dao/OAuthAppDAO.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/dao/SQLQueries.java
components/oauth/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/internal/OAuthApplicationMgtListener.java

https://wso2.org/jira/browse/IDENTITY-4240

Fixed - IDENTITY-4240

---

components/identity-core/org.wso2.carbon.identity.core.ui/src/main/resources/web/identity/validation/js/identity-validate.js

This reverts commit a3a3ff43db41ad8a64625abe3dad4ee8e2a1da67.

Revert "Fixing IDENTITY-3948"

---

components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/servlet/SAMLSSOProviderServlet.java
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/util/SAMLSSOUtil.java

validated ACS in passivemode to check whether the procided acs in request is in ACS Url list

Fix for 4256

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/TenantDataManager.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/tenant_refresh_endpoint.jsp
components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/listener/AuthenticationEndpointTenantActivityListener.java

Fix for Tenant List Dropdown Feature Pushed Parameters

Fix for Tenant List Dropdown Feature Pushed Parameters

---

components/agents/org.wso2.carbon.identity.sso.agent/src/main/java/org/wso2/carbon/identity/sso/agent/openid/OpenIDManager.java
components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/facebook/FacebookAuthenticator.java
components/application-authenticators/org.wso2.carbon.identity.application.authenticator.social/src/main/java/org/wso2/carbon/identity/application/authenticator/social/google/GoogleOAuth2Authenticator.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/resources/EndpointConfig.properties
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/resources/org/wso2/carbon/identity/application/authentication/endpoint/i18n/Resources.properties
components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/domain.jsp
components/entitlement/org.wso2.carbon.identity.entitlement.common/src/main/java/org/wso2/carbon/identity/entitlement/common/InMemoryPersistenceManager.java
components/entitlement/org.wso2.carbon.identity.entitlement.common/src/main/java/org/wso2/carbon/identity/entitlement/common/util/CarbonEntityResolver.java
components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/pap/PAPPolicyReader.java
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/java/org/wso2/carbon/idp/mgt/ui/util/IdPManagementUIUtil.java
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit-finish-local.jsp
components/idp-mgt/org.wso2.carbon.idp.mgt.ui/src/main/resources/web/idpmgt/idp-mgt-edit-local.jsp
components/openid/org.wso2.carbon.identity.provider/src/main/java/org/wso2/carbon/identity/provider/openid/OpenIDServerAssociationStore.java
components/policy-editor/org.wso2.carbon.policyeditor/src/main/java/org/wso2/carbon/policyeditor/PolicyEditorService.java
components/policy-editor/org.wso2.carbon.policyeditor/src/main/java/org/wso2/carbon/policyeditor/util/CarbonEntityResolver.java
components/sso-saml/org.wso2.carbon.identity.sso.saml.ui/src/main/resources/web/sso-saml/add_service_provider.jsp
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/admin/SAMLSSOConfigAdmin.java
components/sso-saml/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/util/SAMLSSOUtil.java
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/UserRegistrationService.java
components/user-mgt/org.wso2.carbon.identity.user.registration/src/main/java/org/wso2/carbon/identity/user/registration/util/CarbonEntityResolver.java
components/user-mgt/org.wso2.carbon.user.mgt/src/main/java/org/wso2/carbon/user/mgt/bulkimport/CSVUserBulkImport.java
components/user-store/org.wso2.carbon.user.cassandra/src/main/java/org/wso2/carbon/user/cassandra/Util.java
components/workflow-mgt/org.wso2.carbon.identity.workflow.mgt.ui/src/main/resources/web/workflow-mgt/add-association.jsp
service-stubs/identity/org.wso2.carbon.identity.sso.saml.stub/src/main/resources/IdentitySAMLSSOConfigService.wsdl

Reformatted code.

---

components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/step/impl/DefaultStepHandler.java
components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkConstants.java

Included error code in the redirect url when multi-option is enabled.

Fix for IDENTITY-4326
